# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:magnumopus rig_hash set value 'fd4ad0bc7874169901f16bb58e38c9d2250369b27e2cad1d07cc1465151b16b9'
scoreboard objectives add aj.ritual.frame dummy