# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:magnumopus rig_hash set value '552f4357ad0894649822bf684799d106a4c4be067a0498bef50ab17898772964'
scoreboard objectives add aj.ritual.frame dummy