# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'fd4ad0bc7874169901f16bb58e38c9d2250369b27e2cad1d07cc1465151b16b9'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack