# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '552f4357ad0894649822bf684799d106a4c4be067a0498bef50ab17898772964'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack