# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.magnumopus.node.circle_outside] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_circle_outside set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.magnumopus.node.triangle] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_triangle set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.magnumopus.node.square] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_square set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.magnumopus.node.circle_inside] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_circle_inside set from storage animated_java:gu out